// micro-frontend-vue/src/App.vue
<script setup>
import HelloWorld from "./components/HelloWorld.vue";
</script>

<template>
  <div>
    {{ message }}
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

<script>
export default {
  data() {
    return {
      message: "",
    };
  },
  mounted() {
    // Listen for the message from Micro-frontend 1 via the global event bus
    window.eventBus?.on("message-to-micro-frontend-2", (msg) => {
      this.message = msg;
    });
  },
  beforeDestroy() {
    window.eventBus.off("message-to-micro-frontend-2");
  },
};
</script>

// micro-frontend-react/src/App.jsx
import { useState, useEffect } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);
  useEffect(() => {
    // Send a message via the global event bus
    const message = "Hello from Micro-frontend 1";
    window.eventBus?.emit("message-from-micro-frontend-1", message);
  }, []);
  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}

export default App;
